[tool.bumpversion]
current_version = "2.5.3"
parse = '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(?:-(?P<build>\d+))?'
serialize = ["{major}.{minor}.{patch}-{build}",
            "{major}.{minor}.{patch}"]
commit = true
tag = true
tag_message = "{new_version}"
allow_dirty = true

[tool.bumpversion.part.build]
independent = true
optional_value = "0"

[tool.bumpversion.part.release]
optional_value = "beta"
values = [
    "alpha",
    "beta",
    "rc1",
    "rc2",
    "rc3",
]

[[tool.bumpversion.files]]
filename = "setup.py"

[[tool.bumpversion.files]]
filename = "README.md"

[[tool.bumpversion.files]]
filename = "corems/__init__.py"


[[tool.bumpversion.files]]
filename = ".gitlab-ci.yml"


[[tool.bumpversion.files]]

filename = ".gitlab-ci.yml"
search = 'CONTAINER_TAG: "{current_version}"'
replace = 'CONTAINER_TAG: "{new_version}"'

