metadata_file = "path/to/metadata/spreadsheet.csv"
data_dir = "path/to/directory/where/data/lives/"
ref_calibration_path = "path/to/reference/calibration/file.ref"
raw_data_object_type = "LC-DDA-MS/MS Raw Data"
processed_data_object_type = "FT ICR-MS Analysis Results"
registration_file = "path/to/where/database/dump/lives.json"
execution_resource = "EMSL-RZR"
field_strength = 7
workflow_version = "2.2.3"
config_path = "enviroMS/nmdc_metadata_generation/config.yaml"
